# Generated by Django 2.0.6 on 2018-06-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_main', '0006_auto_20180614_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='广告标题')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ad_images', verbose_name='广告图片')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('index', models.IntegerField(default=1, verbose_name='顺序')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '广告轮播图',
                'verbose_name_plural': '广告轮播图',
            },
        ),
    ]
