# Generated by Django 2.0.6 on 2018-06-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_main', '0007_adimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimages',
            name='url',
            field=models.URLField(help_text='可以为本站URL地址或者外部网站地址！', verbose_name='链接地址'),
        ),
    ]
