# Generated by Django 2.1.2 on 2018-10-26 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_main', '0008_auto_20180627_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='无分类', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms_main.Category', verbose_name='文章分类'),
        ),
    ]
